pagopa/idpay-onboarding-workflow

.github/workflows/anchore.yml

* Fixed anchore.yml
* Forced reactor-netty-core and reactor-netty-http to 1.1.7
* Reverted reactor-netty-core and reactor-netty-http to 1.1.6

fix: fixed anchore + cve fixes (#89)

---

src/main/java/it/gov/pagopa/common/config/JsonConfig.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/DecryptCfDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/ErrorDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/OnboardingRejectionReason.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/UnsubscribeBodyDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/rule/trx/DayOfWeekDTO.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/onboarding/workflow/BaseIntegrationTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/event/consumer/OutcomeConsumerIntegrationTest.java

* fixed json deserialization bug
* fixed ObjectMapper config

fix: fixed json deserialization bug (#106)

---

.github/workflows/release.yml

This PR add prod environment to Release github action.

docs: IDP-1483 release on JIRA

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/anchore.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
.releaserc.json
Dockerfile
helm/Chart.yaml
helm/values.yaml

fix: promotion UAT

---

helm/Chart.lock

chore: [IDP-1690] add helm chart lock

---

helm/Chart.lock

This PR proposes to add the helm chart lock file.

chore: [IDP-1690] add helm chart lock (#160)

---

pom.xml

This PR is aimed to trigger a new release. There is no substantial update

fix: minor changes

---

helm/Chart.lock
pom.xml

fix: promotion to prod

---

.github/CODEOWNERS

chore: promotion to uat - add codeowners

---

.github/CODEOWNERS
pom.xml

chore: promotion to prod - add codeowners

---

src/main/java/it/gov/pagopa/onboarding/workflow/repository/OnboardingRepository.java
src/main/java/it/gov/pagopa/onboarding/workflow/repository/OnboardingSpecificRepository.java
src/main/java/it/gov/pagopa/onboarding/workflow/repository/OnboardingSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java

The purpose of this PR is only testing a delete method for technical analysis

feat: Test paged delete

---

src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java

The purpose of this PR is only testing a delete method for technical analysis
Changed page size 

feat: modified pageSize

---

src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java

Reverts pagopa/idpay-onboarding-workflow#171

Revert "feat: Test paged delete"

---

src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java

Reverts pagopa/idpay-onboarding-workflow#170

feat: Revert "feat: modified pageSize"

---

src/main/java/it/gov/pagopa/onboarding/workflow/repository/OnboardingRepository.java
src/main/java/it/gov/pagopa/onboarding/workflow/repository/OnboardingSpecificRepository.java
src/main/java/it/gov/pagopa/onboarding/workflow/repository/OnboardingSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java

Reverts pagopa/idpay-onboarding-workflow#169

feat: Revert "feat: Test paged delete"

---

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

IDP-1765 allow mongo RequestRateTooLarge exception always retryable for selected API

feat: IDP-1765 selected API retryable

---

src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/InitiativeGeneralDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/connector/AdmissibilityRestClientTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java
src/test/resources/mappings/get_beneficiary_view.json

This PR is related to the task [IDP-1747](https://pagopa.atlassian.net/browse/IDP-1747) about the adjustment of ranking onboarding family unit
-  Update checks for onboarding with status demanded
[IDP-1747]: https://pagopa.atlassian.net/browse/IDP-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Idp 1747 adeguamento be onboarding

---

src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

The purpose of this PR is to increase onboarding coverage with new tests.
- new junits added to increase coverage on onboarding checks

fix: update junit for coverage increase

---

src/main/java/it/gov/pagopa/onboarding/workflow/dto/OnboardingStatusCitizenDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/controller/OnboardingControllerTest.java

This PR is related to task [IDP-1823](https://pagopa.atlassian.net/browse/IDP-1823)
- Added familyId in api getOnboardingList
[IDP-1823]: https://pagopa.atlassian.net/browse/IDP-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IDP-1823] added familyId in response to api getOnboardingsList

---

src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

The purpose of this PR is to fix the management of onboarding when the user status is eligible_ko 
- add a check if the rejected reason is budget out of ranking then set status to ELIGIBLE_KO otherwise set it to ONBOARDING_KO

fix: completeOnboarding when eligible_ko

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/onboarding/workflow/BaseIntegrationTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

The purpose of this pr is to change the method of deletion from the database from a bulk delete to a paged delete.
- Modified Method
- Added env values
- Modified JUnit tests

fix: Idp 1818 delete paginata

---

pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
src/test/java/it/gov/pagopa/common/mongo/DummySpringRepository.java
src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

fix: Idp 2003 fix mongo retry when anonymous repo

---

.grype.yaml
Dockerfile
pom.xml
src/main/resources/application.yml

fix: Idp 2016 fix CVE

---

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/event/consumer/OutcomeConsumerIntegrationTest.java

fix: IDP-2003 mongo retry when bulk writing

---

.grype.yaml
Dockerfile
pom.xml
postman/idpay-onboarding-workflow-e2e.postman_collection.json
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/DummySpringRepository.java
src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/event/consumer/OutcomeConsumerIntegrationTest.java

fix: Release dev

---

.github/CODEOWNERS
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestSyncClient.java
src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
src/test/java/it/gov/pagopa/onboarding/workflow/BaseIntegrationTest.java
src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
src/test/resources/mongodbEmbeddedDisabled.properties

chore: IDP-2102 configuring a single mongodb instance for all tests

---

.github/CODEOWNERS
Dockerfile
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestSyncClient.java
src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
src/test/java/it/gov/pagopa/onboarding/workflow/BaseIntegrationTest.java
src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
src/test/resources/mongodbEmbeddedDisabled.properties

chore: Release dev

---

src/main/java/it/gov/pagopa/onboarding/workflow/constants/OnboardingWorkflowConstants.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

- Extend the date of onboarding to family member

fix: Idp 2107 come membro di un nucleo invitato voglio poter aderire alliniziativa anche quando il periodo di adesione e terminato

---

src/main/java/it/gov/pagopa/onboarding/workflow/constants/OnboardingWorkflowConstants.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

Promotion to UAT
- emptying kafka topic at each test + reduced common test timings

feat: Promote to UAT

---

postman/idpay-onboarding-workflow-e2e.postman_collection.json

Promotion to UAT
- [Task IDP-2154](https://pagopa.atlassian.net/browse/IDP-2154)

fix: Promote to UAT

---

src/main/java/it/gov/pagopa/common/web/dto/ErrorDTO.java
src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java
src/main/java/it/gov/pagopa/common/web/exception/ServiceException.java
src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandler.java
src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionPayload.java
src/main/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandler.java
src/main/java/it/gov/pagopa/onboarding/workflow/config/OnboardingWorkflowErrorManagerConfig.java
src/main/java/it/gov/pagopa/onboarding/workflow/connector/InitiativeRestConnectorImpl.java
src/main/java/it/gov/pagopa/onboarding/workflow/connector/admissibility/AdmissibilityRestConnectorImpl.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/AdmissibilityInvocationException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/InitiativeBudgetExhaustedException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/InitiativeInvalidException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/InitiativeInvocationException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/InitiativeNotFoundException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/InitiativeOnboardingException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/OperationNotAllowedException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/PDNDConsentDeniedException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/PDVInvocationException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/PageSizeNotAllowedException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/SelfDeclarationCrtieriaException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/UserNotInWhitelistException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/UserNotOnboardedException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/UserSuspensionOrReadmissionException.java
src/main/java/it/gov/pagopa/onboarding/workflow/exception/custom/UserUnsubscribedException.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
src/test/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandlerTest.java
src/test/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandlerTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/controller/OnboardingControllerTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

feat: handle http errors from service

---

.grype.yaml
Dockerfile
pom.xml
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
src/test/java/it/gov/pagopa/onboarding/workflow/BaseIntegrationTest.java

fix: IDP-2196 fix Cve

---

postman/idpay-onboarding-workflow-e2e.postman_collection.json

Task [IDP-2129](https://pagopa.atlassian.net/browse/IDP-2129)
- removed real cf from test
[IDP-2129]: https://pagopa.atlassian.net/browse/IDP-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [IDP-2129] remove real cf from postman

---

src/main/java/it/gov/pagopa/onboarding/workflow/dto/EvaluationDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/InitiativeGeneralDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/rule/refund/AccumulatedAmountDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/rule/trx/RewardLimitsDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/rule/trx/ThresholdDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/event/consumer/OutcomeConsumerTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/event/producer/OutcomeProducerTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

fix: [IDP-2499] Management decimal amounts

---

.grype.yaml
Dockerfile
helm/values-dev.yaml
helm/values.yaml
pom.xml
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV

chore: fix-cve

---

.grype.yaml
Dockerfile
helm/values-dev.yaml
helm/values.yaml
pom.xml
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV
[PR](https://github.com/pagopa/idpay-onboarding-workflow/pull/241)

chore: Promote to Uat

---

pom.xml

chore: fix CVE

---

Dockerfile

- Update appInsights agent to fix cve

chore: fix cve (#248)

---

src/main/java/it/gov/pagopa/onboarding/workflow/dto/SelfConsentDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/SelfConsentTextDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/SelfCriteriaTextDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/SelfDeclarationItemsDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/model/SelfDeclarationText.java
src/main/java/it/gov/pagopa/onboarding/workflow/model/SelfDeclarationTextValues.java
src/main/java/it/gov/pagopa/onboarding/workflow/repository/SelfDeclarationTextRepository.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

feat: Idp 2594 add self criteria text

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/onboarding/workflow/dto/SelfConsentDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/SelfConsentTextDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/SelfCriteriaTextDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/initiative/SelfDeclarationItemsDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/model/SelfDeclarationText.java
src/main/java/it/gov/pagopa/onboarding/workflow/model/SelfDeclarationTextValues.java
src/main/java/it/gov/pagopa/onboarding/workflow/repository/SelfDeclarationTextRepository.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

- Added self criteria
- Added self declaration 

feat: Promote to UAT Release dev

---

pom.xml
src/main/java/it/gov/pagopa/onboarding/workflow/dto/OnboardingDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

feat: added serviceId on OnboardingDTO

---

src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

fix: update selfDeclaration

---

helm/values-prod.yaml
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

chore: promote to Main

---

src/main/java/it/gov/pagopa/onboarding/workflow/model/SelfDeclaration.java
src/main/java/it/gov/pagopa/onboarding/workflow/model/SelfDeclarationMultiValues.java
src/main/java/it/gov/pagopa/onboarding/workflow/repository/SelfDeclarationRepository.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

fix: IDP 2656 saved multi self declaration consent

---

.github/workflows/release.yml
.github/workflows/snapshot-docker.yml
src/main/java/it/gov/pagopa/onboarding/workflow/controller/OnboardingControllerImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

chore: add release and snapshot-docker file

---

Dockerfile
pom.xml

chore: [IDP-2676 ]update jdk to 21

---

src/main/java/it/gov/pagopa/onboarding/workflow/dto/SelfConsentDTO.java

fix multi_consent name in SelfConsentDTO

fix: Upbe 121 fix

---

src/main/java/it/gov/pagopa/onboarding/workflow/controller/OnboardingController.java
src/main/java/it/gov/pagopa/onboarding/workflow/controller/OnboardingControllerImpl.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/ConsentPutDTO.java
src/main/java/it/gov/pagopa/onboarding/workflow/dto/mapper/ConsentMapper.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingService.java
src/main/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceImpl.java
src/test/java/it/gov/pagopa/onboarding/workflow/controller/OnboardingControllerImplTest.java
src/test/java/it/gov/pagopa/onboarding/workflow/service/OnboardingServiceTest.java

adding userMail and channel to saveOnboarding

feat: [UPBE-182] adding userMail and channel to saveOnboarding
